"""delete column position

Revision ID: 20fbd3b92771
Revises: 411720ea3de4
Create Date: 2024-11-23 11:24:49.289508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20fbd3b92771'
down_revision = '411720ea3de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', mysql.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
